services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: showFiap
      POSTGRES_USER: showFiap
      POSTGRES_PASSWORD: showFiap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: